### ISSUE TITLE
Issue updating VIA keymap

### ISSUE THREAD

**Issue by gtg465x** [jjesuscastro/qmk_firmware#1]
Hi, I found your README on updating a VIA keymap to label custom keycodes. I followed it and it works, but if I close and then re-open VIA, the custom keycodes tab and labels are gone. What's the trick to getting them to stick?

**Comment by jesusgadai** [comment]
Unfortunately it is a limitation of VIA itself. You will need to import the JSON file whenever you open VIA.

**Comment by jjesuscastro** [comment]
Unfortunately it is a limitation of VIA itself. You will need to import the JSON file whenever you open VIA.

**Comment by gtg465x** [comment]
I wonder if there’s a way to flash it permanently to the EEPROM. VIA’s developer documentation is horrible.
